#
# Circuit compiler for the Faerieplay hardware-assisted secure
# computation project at Dartmouth College.
#
# Copyright (C) 2003-2007, Alexander Iliev <sasho@cs.dartmouth.edu> and
# Sean W. Smith <sws@cs.dartmouth.edu>
#
# All rights reserved.
#
# This code is released under a BSD license.
# Please see LICENSE.txt for the full license and disclaimers.
#

include config.make

# Set a bunch of make variables
include do_setup.make

# generated by cabal
EXES = dist/build/fc++/fc++ dist/build/sfdlc/sfdlc

# Generated by update-versions.pl and used to track versions across the source
# files.
VERSFILE = Faerieplay/Version.hs

all: $(VERSFILE) $(EXES) doc
#	@echo srcs = $(SRCS)
#	@echo vers file = $(VERSFILE)

install: all
	install -p $(EXES) $(DIST_ROOT)/bin/


$(EXES): | init
#	HFLAGS="$(GHCFLAGS)" hmake -d$(ODIR) -ghc $(PACKS) sfdlc
	cabal install
#	$(GHC) --make $(GHCFLAGS) -o $@ Faerieplay/sfdlc.hs


SRCS = $(shell find $(CURDIR)/Faerieplay -name '*.hs' -o -name '*.cf') 


init:
	mkdir -p $(ODIR)

.PHONY: init


doc:
	$(MAKE) -C doc
.PHONY: doc


##############################
## version management
##############################

# Both $(VERSFILE) and $(VERSFILE).tok are kept in svn. $(VERSFILE).tok is a
# static template, while $(VERSFILE) is updated with version summary info, so it
# changes if any other source file changes. Then upon checkin, svn updates the
# version info in $(VERSFILE) to be the same as the latest modified source file.

$(VERSFILE): $(VERSFILE).tok $(SRCS)
	$(CURDIR)/update-versions.pl < $(VERSFILE).tok > $(VERSFILE) $^


ifdef TOOLS_DIR
# alex and happy are not quite smart enough to find their helper files relative
# to the executable, so we have to tell them.
ifneq ($(empty), $(wildcard $(TOOLS_DIR)/$(ALEX_SUBDIR)))
ALEXFLAGS += --template=$(TOOLS_DIR)/$(ALEX_SUBDIR)
endif

ifneq ($(empty), $(wildcard $(TOOLS_DIR)/$(HAPPY_SUBDIR)))
HAPPYFLAGS += --template=$(TOOLS_DIR)/$(HAPPY_SUBDIR)
endif

endif


BNFCDIR = $(BNFC_LANG_DIR)

# Now using BNFC 2.3b features, though only for artifact layout.
BNFCROOTS=Abs Lex Print Test ErrM Par Skel
bnfc_files=$(patsubst %,$(BNFC_LANG_DIR)/%.hs,$(word 1,$(BNFCROOTS)))
$(bnfc_files): $(source_lang).cf
	bnfc -haskell -d -p $(BNFC_PACKAGE_ROOT) $<
	(cd $(BNFCDIR); pdflatex Doc.tex)
	ed $(BNFCDIR)/Abs.hs < add-bnfc-derives.ed
	ghc --make $(BNFCDIR)/Test.hs -o Faerieplay/Bnfc/Sfdl/Test

bnfc: $(bnfc_files)



%.o: %.hs
	$(GHC) -c $(GHCFLAGS) $<


$(ODIR)/%.o: %.hs
#	HFLAGS="$(GHCFLAGS)" hmake -ghc $(PACKS) $<
	$(GHC) -c $(GHCFLAGS) $<

%.hi: %.hs
	$(GHC) -E -ddump-minimal-imports $(GHCFLAGS) $< > $@


# this make shouldnt look at the compiled sfdlc file--hmake or ghc do that.
.PHONY: $(EXE) bnfc dep

clean:
	$(MAKE) -C doc clean
	$(RM) -r $(ODIR)/*
	cabal clean
#	HFLAGS="$(GHCFLAGS)" hmake -package fgl -d$(ODIR) -clean sfdlc


tags: TAGS

# hasktags is no longer part of ghc, since 6.12.
# but can install it from hackage:
# cabal install hasktags
# other tags options:
# http://www.haskell.org/haskellwiki/Tags#Haskell_tag_generators
TAGS: $(SRCS)
	hasktags --etags $^

# have this here, as a standard target, even if empty.
dep:

# to make postscript of a circuit (or any) gviz file:
#  dot -Tps cct.gviz -o cct.ps
