{-# OPTIONS_GHC -fglasgow-exts #-}
-- edited by sasho's add-bnfc-derives.ed script,
-- to add Data and Typeable derivations.
module Faerieplay.Bnfc.Sfdl.Abs where
import Data.Typeable            (Typeable)
import Data.Generics            (Data)

-- Haskell module generated by the BNF converter


newtype Ident = Ident String deriving (Data,Typeable,Read,Eq,Ord,Show)
data Prog =
   Prog Ident [Dec]
  deriving (Data,Typeable,Read,Eq,Ord,Show)

data Dec =
   ConstDecl Ident Exp
 | TypeDecl Ident Typ
 | VarDecl Typ [Ident]
 | FunDecl Typ Ident [TypedName] [Dec] [Stm]
 | TypedFunDecl Typ Ident [TypedName] Typ [Dec] [Stm]
  deriving (Data,Typeable,Read,Eq,Ord,Show)

data Typ =
   IntTConcrete SizeExp
 | IntT Exp
 | GenIntT
 | BoolT
 | VoidT
 | StructT [TypedName]
 | EnumT [Ident]
 | ArrayT Typ Exp
 | RefT Typ
 | SimpleT Ident
 | FuncT Typ [Typ]
 | RedIntT Integer
 | RedArrayT Typ Integer
  deriving (Data,Typeable,Read,Eq,Ord,Show)

data TypedName =
   TypedName Typ Ident
  deriving (Data,Typeable,Read,Eq,Ord,Show)

data Stm =
   SBlock [Dec] [Stm]
 | SAss LVal Exp
 | SPrint String [Exp]
 | SFor Ident Exp Exp Stm
 | SIf Exp Stm
 | SIfElse Exp Stm Stm
  deriving (Data,Typeable,Read,Eq,Ord,Show)

data LVal =
   LVal Exp
 | LValT Typ LVal
  deriving (Data,Typeable,Read,Eq,Ord,Show)

data Exp =
   EIdent Ident
 | EInt Integer
 | ETrue
 | EFalse
 | EArr Exp Exp
 | EStruct Exp Exp
 | EFunCall Ident [FunArg]
 | ENot Exp
 | ENeg Exp
 | EBNot Exp
 | ETimes Exp Exp
 | EDiv Exp Exp
 | EMod Exp Exp
 | EPlus Exp Exp
 | EMinus Exp Exp
 | ESL Exp Exp
 | ESR Exp Exp
 | ELt Exp Exp
 | EGt Exp Exp
 | ELtEq Exp Exp
 | EGtEq Exp Exp
 | EEq Exp Exp
 | ENeq Exp Exp
 | EBAnd Exp Exp
 | EBXor Exp Exp
 | EBOr Exp Exp
 | EAnd Exp Exp
 | EOr Exp Exp
 | ECoerce Integer Exp
 | EGetBit Exp Exp
 | ExpT Typ Exp
  deriving (Data,Typeable,Read,Eq,Ord,Show)

data SizeExp =
   SEIdent Ident
 | SEInt Integer
 | SEFunCall Ident [SizeFunArg]
 | SETimes SizeExp SizeExp
 | SEPlus SizeExp SizeExp
 | SEMinus SizeExp SizeExp
  deriving (Data,Typeable,Read,Eq,Ord,Show)

data FunArg =
   FunArg Exp
  deriving (Data,Typeable,Read,Eq,Ord,Show)

data SizeFunArg =
   SizeFunArg SizeExp
  deriving (Data,Typeable,Read,Eq,Ord,Show)

